- name: Install monit packages
  apt: name={{item}} state=present
  with_items:
    - monit

- name: Monit | Copy the sshd/nginx monit service files
  template:
    src: "etc_monit_conf.d_{{item}}.j2"
    dest: "/etc/monit/conf.d/{{item}}"
  with_items:
    - sshd
    - monit
    - nginx
    - disk
  notify:
    - restart monit

- name: Allow monit traffic
  tags:
    - firewall
  ufw: rule=allow port={{monit_port}} proto=tcp

- name: Start Monit
  become: yes
  service: name=monit state=running enabled=yes
