- name: Install postgres
  apt: name={{item}} state=present
  become: True
  with_items:
    - postgresql-server-dev-9.5
    - postgresql-9.5
    - postgresql-contrib-9.5
  tags:
    - postgresql

- name: Config security for postgres user
  lineinfile:
    dest: /etc/postgresql/9.5/main/pg_hba.conf
    regexp: '^local\s+all\s+postgres+\s+peer'
    line: "local   all             postgres                                trust"
    state: present
  become: True
  tags:
    - postgresql

- service: name=postgresql state=restarted enabled=yes
  become: True
  tags:
    - postgresql
